/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_knuth_multimediaremote_server_model_remotes_NativeRemote */

#ifndef _Included_org_knuth_multimediaremote_server_model_remotes_NativeRemote
#define _Included_org_knuth_multimediaremote_server_model_remotes_NativeRemote
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_knuth_multimediaremote_server_model_remotes_NativeRemote
 * Method:    nPausePlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_knuth_multimediaremote_server_model_remotes_NativeRemote_nPausePlay
  (JNIEnv *, jobject);

/*
 * Class:     org_knuth_multimediaremote_server_model_remotes_NativeRemote
 * Method:    nStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_knuth_multimediaremote_server_model_remotes_NativeRemote_nStop
  (JNIEnv *, jobject);

/*
 * Class:     org_knuth_multimediaremote_server_model_remotes_NativeRemote
 * Method:    nNextTrack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_knuth_multimediaremote_server_model_remotes_NativeRemote_nNextTrack
  (JNIEnv *, jobject);

/*
 * Class:     org_knuth_multimediaremote_server_model_remotes_NativeRemote
 * Method:    nPreviousTrack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_knuth_multimediaremote_server_model_remotes_NativeRemote_nPreviousTrack
  (JNIEnv *, jobject);

/*
 * Class:     org_knuth_multimediaremote_server_model_remotes_NativeRemote
 * Method:    nVolUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_knuth_multimediaremote_server_model_remotes_NativeRemote_nVolUp
  (JNIEnv *, jobject);

/*
 * Class:     org_knuth_multimediaremote_server_model_remotes_NativeRemote
 * Method:    nVolDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_knuth_multimediaremote_server_model_remotes_NativeRemote_nVolDown
  (JNIEnv *, jobject);

/*
 * Class:     org_knuth_multimediaremote_server_model_remotes_NativeRemote
 * Method:    nMute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_knuth_multimediaremote_server_model_remotes_NativeRemote_nMute
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
